const tintColor = '#F15A24';

export default {
  theme: '#11b719',
  text: '#F15A24',
  secondaryColor: '#2F1463',
  white: '#fff',
  black: '#000000',
  tint: tintColor,
  blue: '#4b8efa',
  darkBlue: '#1f2e47',
  lightBlue: '#8db6f7',
  lightGray: '#999696',
  tabIconDefault: '#bfbfbf',
  success: 'green',
  danger: '#D93025',
  tabIconSelected: tintColor,
  borderColor: '#E4E4E4',
  colors: [
    {value: 'Brown'},
    {value: 'Black'},
    {value: 'Red'},
    {value: 'Red (Ginger)'},
    {value: 'White'},
    {value: 'Gold'},
    {value: 'Yellow'},
    {value: 'Cream'},
    {value: 'Grey'},
    {value: 'Blue'},
    {value: 'Blue / Grey'},
    {value: 'Albino'},
    {value: 'Cinnamon'},
    {value: 'Fawn'},
  ],
};
